server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        #Route Mapping
        - id: spring-boot-validaion
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
        #Route Mapping
        - id: pdf-signature-server
          uri: http://localhost:8081
          predicates:
            - Path=/pdf/v1/**
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO